easy_admin:
    entities:
        SiteLoading:
            class: App\Entity\SiteLoading
            label: Chargement du site
            list:
                fields:
                    - { property: 'logoVideo', template: 'logoVideo.html.twig', base_path: '%app.path.videos%' }
            form:
                fields:
                    - { property: 'logoVideoFile', type: 'vich_file' }
        SiteHistory:
            class: App\Entity\SiteHistory
            label: Histoire de la base
        BaseEntity:
            class: App\Entity\BaseEntity
            label: Entité BSM
            list:
                fields:
                    - { property: 'id' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%', label: 'Image principale' }
                    - { property: 'logo', type: 'image', base_path: '%app.path.images%', label: 'Logo' }
                    - { property: 'description' }
                    - { property: 'descriptionCurrentEvent', label: "Description évenement en cours" }
                    - { property: 'mapUrl', label: "Url croquis" }
            show:
                fields:
                    - { property: 'id' }
                    - { property: 'image', type: 'image', base_path: '%app.path.images%', label: 'Image principale' }
                    - { property: 'logo', type: 'image', base_path: '%app.path.images%', label: 'Logo' }
                    - { property: 'description' }
                    - { property: 'descriptionCurrentEvent', label: "Description évenement en cours" }
                    - { property: 'mapUrl', label: "Url croquis" }
            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'logoFile', type: 'vich_image' }
                    - { property: 'description' }
                    - { property: 'descriptionCurrentEvent', label: "Description évenement en cours" }
                    - { property: 'mapUrl', label: "Url croquis" }
    site_name: 'Base 3 en 1'
    user:
        display_name: false
        display_avatar: false
